included:
  - MovieApp
  - API
  - Helpers
excluded:
  - .git
  - Pods
analyzer_rules:
  - unused_declaration
  - unused_import
disabled_rules:
  - trailing_whitespace
  - vertical_whitespace_opening_braces
  - vertical_whitespace_closing_braces
  - sorted_imports
  - multiple_closures_with_trailing_closure
  - unneeded_parentheses_in_closure_argument
  - strong_iboutlet
  - prohibited_interface_builder
  - modifier_order
  - file_header
  - pattern_matching_keywords
  - fatal_error
  - discouraged_object_literal
  - object_literal
opt_in_rules:
  - anyobject_protocol
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - joined_default_parameter
  - legacy_random
  - let_var_whitespace
  - last_where
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - nimble_operator
  - nslocalizedstring_key
  - number_separator
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - private_action
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - static_operator
  - toggle_bool
  - unavailable_function
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - xct_specific_matcher
  - yoda_condition

identifier_name:
  excluded:
    - id

number_separator:
  minimum_length: 5

line_length:
  - 300 #warning
  - 400 #error

function_body_length:
  - 50 #warning
  - 100 #error
  
type_body_length:
  - 200 #warning
  - 300 #error
  
lower_acl_than_parent:
  - 2 #warning
  - 3 #error

identifier_name:
  min_length:
    warning: 1
  max_length:
    warning: 35
    
file_length:
  - 400 #warning
  - 700 #error

cyclomatic_complexity:
  - 15 #warning
  - 25 #error
  
nesting:
  type_level:
    warning: 2
    error: 3

large_tuple:
 - 3
 - 4
  
custom_rules:
  fatal_error:
    name: Fatal Error
    excluded: "Tests/*"
    message: Prefer using `queuedFatalError` over `fatalError` to avoid leaking compiler host machine paths.
    regex: \bfatalError\b
    match_kinds:
      - identifier
    severity: error

